### PR TITLE
Generic: fix setting start pose

### PR DESCRIPTION
**Pull request by D-Alex**
The start pos was only set if the task was already running.
Now, the normal apply config workflow is supported.

### CODE REVIEW

**Comment by D-Alex** [comment]
@dettmann was there a particular reason why the property start_pos was flagged as dynamic?

**Comment by dettmann** [comment]
Yep, because I'm using this port to initially sync the odometry pose to some ground truth data (sim, motion trackings system). This transformation is not known beforehand and is also intended to be reset in some cases

**Comment by D-Alex** [comment]
Looking into the implementation, the variable is only used if a start - stop cycle is performed. Therefore, the dynamic flag is not necessary.

**Comment by dettmann** [comment]
If it was not dynamic, would you not have to load a new configuration and reconfigure all the time?

**Comment by D-Alex** [comment]
Actually no, properties are set no matter if they are dynamic or not during all possible task states (stop,running,....). Therefore, the problem is that in the case of a running task you might get a half updated property and also you have to check the property during each updateHook if it was changed. To overcome this, the dynamic property was added. Here, the tooling (orocos.rb) calls a remote method on the task serving as callback function to update the internal state of the task.

In this particular case, there is no need for the dynamic property because the task is not modified while in running state.

**Pull request merged**
