### PR TITLE
added z-position overwrite to improve accurace for spaceclimber

### PR DESCRIPTION
**Pull request by dettmann**

### CODE REVIEW

**Comment by leifole** [comment]
Hm, directly overwriting the z value looks a little bit hacky to me, tailored to a robot-specific problem. Not sure if master ist the right place for this. If drift in z is the problem, one should approach it in a more generic way (otherwise we will have override ports for x and y and all kinds of other variables soon, I fear.

**Comment by dettmann** [comment]
I totally agree. Just needing some input on how to handle this problem properly. So, leave it on an extra branch? To make it more generic is properly hard, though this dirty hack might be an improvement for all spaceclimber-like walking systems ...

**Comment by leifole** [comment]
Still a hack, but more generic would be to use RigidBodyState type for a general post-estimate override port. I think we need to discuss this further, maybe in the AG. Until then, I would create a post-override branch, rename the port and switch the type from double to RBS.
And contact the maintainers ;-)

**Comment by chhtz** [comment]
Not sure if this is required anymore or if a better solution was found.

I also don't really like adding this as an option to an odometry task. Odometry is expected to drift, so a better solution IMO is to have another pose estimation task which, e.g., fuses other measurements (e.g., height from a map or from GPS or a barometer).

I close this now, if someone disagrees feel free to re-open.

**Pull request closed without merging**
