### PR TITLE
Changed frame names of in and outgoing transforms

### PR DESCRIPTION
**Pull request by skasperski**
Will now subscribe to "imu_body" => "imu_world", but publish "body" => "odometry" to avoid loops in the transformer graph.

Also had to fix stream aligner usage.

Only tested "Skid" task in simulation so far.

### CODE REVIEW

**Comment by saarnold** [comment]
There is no need in changing this variable names. For every frame that is defined in the .orogen file, orogen will generate an property that allows users to set the actual frame name.
E.g. transformation 'body', 'odometry' will add a body_frame and a odometry_frame property.
The worst thing in such API changes is that it will force everyone to adapt their scripts and config files.

**Comment by skasperski** [comment]
Frame names are actually used like that and outgoing frame names have been defined as parameters before my changes already. The problem is that IMU source frame and odometry target frame do not necessarily need to be the same. In fact it can create loops in the transformer graph that mess up visualization in vizkit3d. If the old behaviour is desired, it is still possible to set body_frame = imu_body_frame. I can add default parameters, so that a change of configurations is not even necessary to keep the current behaviour.

**Comment by jmachowinski** [comment]
I agree with sascha, do not change the interface of the component. The changes to the internal logic are fine.

**Comment by jmachowinski** [comment]
merged in modified form

**Pull request closed without merging**
